# Generated by Django 4.2.4 on 2023-08-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
