# Generated by Django 4.2.4 on 2023-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcapp', '0002_rename_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CD', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MK', 'Milkshake'), ('PN', 'panner'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Cream')], max_length=2),
        ),
    ]
